### ISSUE TITLE
Incorrect formatting of sitemap url

### ISSUE THREAD

**Issue by BrummbQ** [HiYue/vuepress-plugin-robots#1]
Hi, can you please have a look:

In index.js line 59 you are replacing // by / (I dont know why). This breaks the url and creates an invalid robots.txt, i.e.:

https://host.com/sitemap.xml -> https:/host.com/sitemap.xml

**Comment by pollmix** [comment]
Default option for sitemap produced wrong result. To solve it provide `sitemap: "/sitemap.xml"` explicitly.
